config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#index'

  get 'pages/index'
  get 'pages/people'
  get 'pages/projects'
  get 'pages/publications'
  get 'pages/contact'

  get 'people' => 'people#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get 'publications' => 'publications#index'

  get '/publications/:id/edit' => 'publications#edit'
  get '/publications/indexall' => 'publications#indexall'

  delete '/' => 'sessions#destroy'
  delete '/users' => 'sessions#destroy'
  delete '/people' => 'sessions#destroy'
  delete '/projects' => 'sessions#destroy'
  delete '/publications' => 'sessions#destroy'
  delete '/pages/contact' => 'sessions#destroy'

  get '/login' => 'sessions#new'
  get '/publications/:id/edit' => 'publications#edit'
  get '/publications/indexall' => 'publications#indexall'

  resources :projects
  resources :users
  resources :sessions
  resources :people
  resources :publications

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :title
end

app/models/project.rb
class Project < ActiveRecord::Base
    validates_presence_of :title
    validates_presence_of :description
    validates_presence_of :people
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  validates_presence_of :year
  validates_presence_of :citation
end

app/models/session.rb
class Session < ActiveRecord::Base
    belongs_to :user

    def save_with_session_code
      self.session_code = SecureRandom.urlsafe_base64 unless self.session_code
      self.save
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def people
  end

  def projects
  end

  def publications
  end

  def contact
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
      @people = Person.all
    end

    def show
      @person = Person.find(params[:id])
      respond_to do |format|
          format.html
          format.json {render json: @user}
        end
    end

    def new
        @person = Person.new
    end

    def create
        @person = Person.create(person_params)
        redirect_to @person
    end

    def person_params
      params.require(:person).permit(:name, :title, :site, :contact, :projects)
    end

    def edit
        @person = Person.find(params[:id])
    end

    def update
        @person = Person.find(params[:id])
        respond_to do |format|
            if @person.update(person_params)
                format.html {redirect_to @person, notice: 'Person was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @person.errors, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @person = Person.find(params[:id])
        @person.destroy
        flash[:success] = "Person deleted"
        redirect_to people_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      @projects = Project.all
    end

    def show
      @projects = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.create(project_params)
        redirect_to @project
    end

    def project_params
      params.require(:project).permit(:title, :people, :description)
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        respond_to do |format|
            if @project.update(project_params)
                format.html {redirect_to @project, notice: 'Project was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @project.errors, status: :unprocessable_entity}
            end
        end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
 def index
    @publications = Publication.all
  end

  def indexall
    @publications = Publication.all
  end

  def show
    @publications = Publication.find(params[:id])
  end

  def new
      @publication = Publication.new
  end

  def create
      @publication = Publication.create(publication_params)
      redirect_to @publication
  end

  def publication_params
    params.require(:publication).permit(:year, :citation)
  end

  def edit
      @publication = Publication.find(params[:id])
  end

  def update
      @publication = Publication.find(params[:id])
      respond_to do |format|
          if @publication.update(publication_params)
              format.html {redirect_to publications_path, notice: 'Publication was successfully updated.'}
              format.json {head :no_content}
          else
              format.html {render action: 'edit'}
              format.json {render json: @publication.errors, status: :unprocessable_entity}
          end
      end
  end

  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy
    flash[:success] = "Publication deleted"
    redirect_to publications_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      s = Session.new(user_id: user.id)
      s.save_with_session_code
      cookies.permanent[:session_code] = s.session_code
      redirect_to root_url
    else 
      render text: 'Incorrect email or password.'
    end
  end

  def destroy
    cookies.delete :session_code
    #session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @user}
    end
  end

  def new
    @user = User.new
  end


  include SessionsHelper
  def create
      @user = User.create(user_params)
      s = Session.new(user_id: @user.id)
      s.save_with_session_code
      cookies.permanent[:session_code] = s.session_code
      redirect_to @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

   def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        respond_to do |format|
            if @user.update(user_params)
                format.html {redirect_to @user, notice: 'User was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @user.errors, status: :unprocessable_entity}
            end
        end
    end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user(*args)
    x = Session.includes([:user => (args.nil? ? [] : args)]).find_by(:session_code => cookies[:session_code])
    @current_user = x.nil? ? nil : x.user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/people/_form.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="large-6 medium-6 small-12 columns">
      <% if !current_user.nil? %>
        <%= form_for @person do |u| %>
          <label>Name <%= u.text_field :name, placeholder: 'Name' %></label>
          <label>Title <%= u.text_field :title, placeholder: 'Academic title' %></label>
          <label>Email <%= u.text_field :contact, placeholder: 'Email address' %></label>
          <label>Site <%= u.text_field :site, placeholder: 'Website' %></label>
          <label>Projects <%= u.text_field :projects, placeholder: 'Project 1, Project 2...' %></label>
          <%= u.submit 'Submit', class: 'button' %>
        <% end %>
      <% else %>
        <p>You must be logged in as the administrator for access to this feature.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Edit person</h2>
    </div>
  </div>
</div>

<%= render 'people/form' %>

app/views/people/index.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>People</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
  <% if !current_user.nil? %>
    <div class="large-12 medium-12 small-12 columns"> 
      <%= link_to "Add new person", new_person_path %>
    </div>
  <% end %>
   <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <% @people.each do |p| %>
        <li class = "gridblock">
          <h3><b><%= link_to p.name, p %></b></h3>
          <p><b><%= p.title %></b><br/>
          <%= p.projects %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/people/new.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Create new person</h2>
    </div>
  </div>
</div>

<%= render 'people/form' %>

app/views/people/show.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Profile</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="large-12 medium-12 small-12 columns">
      <%= link_to "Back to people", people_path %>
      <% if !current_user.nil? %>
       | <%= link_to "Edit person", edit_person_path %>
       | <%= link_to 'Delete', @person, method: :delete, data: {confirm: "Are you sure you wish to delete?"} %>
      <% end %>
      <h3><%= @person.name %></h3>
        <p><b>Title:</b> <%= @person.title %><br/>
        <b>Email:</b> <%= @person.contact %><br/>
        <b>Site:</b> <%= @person.site %><br/>
        <b>Projects:</b> <%= @person.projects %></p>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="large-6 medium-6 small-12 columns">
      <% if !current_user.nil? %>
        <%= form_for @project do |p| %>
          <label>Title <%= p.text_field :title, placeholder: 'Project title' %></label>
          <label>People <%= p.text_field :people, placeholder: 'Contributor 1, Contributor 2...' %></label>
          <label>Description <%= p.text_area :description, placeholder: 'Project description' %></label>
          <%= p.submit 'Submit', class: 'button' %>
        <% end %>
      <% else %>
        <p>You must be logged in as the administrator for access to this feature.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Edit project</h2>
    </div>
  </div>
</div>
<%= render 'projects/form' %>

app/views/projects/index.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Projects</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <% if !current_user.nil? %>
      <div class="large-12 medium-12 small-12 columns"> 
        <%= link_to "Add new project", new_project_path %>
      </div>
    <% end %>
   <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <% @projects.each do |p| %>
        <li class = "gridblock">
          <h3><b><%= link_to p.title, p %></b></h3>
          <p><%= p.people %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/new.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>New project</h2>
    </div>
  </div>
</div>

<%= render 'projects/form' %>

app/views/projects/show.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Project</h2>
    </div>

    <div class="large-12 medium-12 small-12 columns">
      <%= link_to 'Back to projects', projects_path %>
      <% if !current_user.nil? %>
       | <%= link_to 'Edit project', edit_project_path %>
       | <%= link_to 'Delete', @project, method: :delete, data: {confirm: "Are you sure you wish to delete?"} %>
      <% end %>
      <h3><%= @projects.title %></h3>
      <p><b>People: </b><%= @projects.people %><br/>
      <b>Description: </b><%= @projects.description %></p>

    </div>
  </div>
</div>

app/views/publications/_form.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="large-6 medium-6 small-12 columns">
    <% if !current_user.nil? %>
       <%= link_to 'Back to publications', publications_path %> 

       
        <%= form_for @publication do |p| %>
          <label>Year <%= p.text_field :year, placeholder: 'Publication year' %></label>
          <label>Publication <%= p.text_area :citation, placeholder: 'Citation' %></label>
          <%= p.submit 'Submit', class: 'button' %>
        <% end %>
      <% else %>
        <p>You must be logged in as the administrator for access to this feature.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/edit.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Edit publication</h2>
    </div>
  </div>
</div>
<%= render 'publications/form' %>

app/views/publications/index.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Publications</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <% if !current_user.nil? %>
    <div class="large-12 medium-12 small-12 columns">
      <%= link_to "Add new publication", new_publication_path %> | <%= link_to "View all", "publications/indexall" %>
    </div>
    <% end %>

    <div id="tabshift">
      <dl id="tabsrow" class="tabs" data-tab>
        <dd class="active"><a href="#panel2014">2014</a></dd>
        <dd><a href="#panel2013">2013</a></dd>
        <dd><a href="#panel2012">2012</a></dd>
        <dd><a href="#panel2011">2011</a></dd>
      </dl>
    </div> <!-- end of tabs shift -->
    
    <div id="tabscontent" class="tabs-content">
      <% @publications.each do |p| %>
        <% $year = p.year %>

        <div class="content active" id="panel2014">
          <% if $year == 2014%>
            <% if !current_user.nil? %>
              <%= link_to "Edit", p %>
            <% end %>
            <p><%= p.citation %></p>
          <% end %>
        </div>

      <div class="content" id="panel2013">
        <% if $year == 2013%>
            <% if !current_user.nil? %>
              <%= link_to "Edit", p %>
            <% end %>
            <p><%= p.citation %></p>
        <% end %>
      </div>

      <div class="content" id="panel2012">
        <% if $year == 2012%>
            <% if !current_user.nil? %>
              <%= link_to "Edit", p %>
            <% end %>
            <p><%= p.citation %></p>
        <% end %>
      </div>

      <div class="content" id="panel2011">
        <% if $year == 2011%>
            <% if !current_user.nil? %>
              <%= link_to "Edit", p %>
            <% end %>
            <p><%= p.citation %></p>
        <% end %>
      </div>

      <% end %>

      </div> <!-- end of tabs content -->
  </div>
</div>

app/views/publications/indexall.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Publications</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 

  <% if !current_user.nil? %>
    <div class="large-12 medium-12 small-12 columns"> 
      <%= link_to "Add new publication", new_publication_path %>
    </div>
      
    <div class="large-12 medium-12 small-12 columns"> 
      <h5><b>2014</b></h5>
        <% @publications.each do |p| %>
          <% $year = p.year %>
          <% if $year == 2014 %>
            <p><%= link_to "Edit", p %><br/>
            <%= p.citation %></p>
          <% end %>
        <% end %>

      <h5><b>2013</b></h5>
        <% @publications.each do |p| %>
          <% $year = p.year %>
          <% if $year == 2013%>
              <p><%= link_to "Edit", p %><br/>
              <%= p.citation %></p>
          <% end %>
        <% end %>

      <h5><b>2012</b></h5>
        <% @publications.each do |p| %>
          <% $year = p.year %>
          <% if $year == 2012%>
              <p><%= link_to "Edit", p %><br/>
              <%= p.citation %></p>
          <% end %>
        <% end %>

      <h5><b>2011</b></h5>
        <% @publications.each do |p| %>
          <% $year = p.year %>
          <% if $year == 2011%>
              <p><%= link_to "Edit", p %><br/>
              <%= p.citation %></p>
          <%end%>
        <% end %>

      <h5><b>Miscellaneous</b></h5>
        <% @publications.each do |p| %>
          <% $year = p.year %>
          <% if $year < 2011 || $year > 2014 %>
            <p><%= link_to "Edit", p %><br/>
            <%= p.citation %></p>
          <% end %>
      <% end %>
    <% else %>
      <div class="large-12 medium-12 small-12 columns"> 
       <p>You must be logged in as the administrator for access to this feature.</p>
      </div>
    <% end %>

    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>New publication</h2>
    </div>
  </div>
</div>

<%= render 'publications/form' %>

app/views/publications/show.html.erb
<div class='row'>
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Publication</h2>
    </div>

    <div class="large-12 medium-12 small-12 columns">
      <%= link_to 'Back to publications', publications_path %>
      <% if !current_user.nil? %>
         | <%= link_to 'Edit', edit_publication_path %> | <%= link_to "Delete", @publication, method: :delete, data: { confirm: "Are you sure you wish to delete?" } %>
      <% end %>
      <p><b>Year: </b><%= @publications.year %><br/>
      <b>Citation: </b><%= @publications.citation %><br/>

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="large-6 medium-6 small-12 columns">
      <% if !current_user.nil? %>
        <%= form_for @user do |u| %>
          <label>Name <%= u.text_field :name, placeholder: 'Name' %></label>
          <label>Email <%= u.text_field :email, placeholder: 'Email address' %></label>
          <label>Password <%= u.password_field :password, placeholder: 'Password' %></label>
          <%= u.submit 'Submit', class: 'button' %>
        <% end %>

      <% else %>
        <p>You must be logged in as the administrator for access to this feature.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Edit user</h2>
    </div>
  </div>
</div>

  <%= render 'users/form' %>

app/views/users/index.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Users</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="large-12 medium-12 small-12 columns">
      <% if !current_user.nil? %>
        <%= link_to "Add new user", new_user_path %>

        <% @user.each do |u| %>
          <p><b><%= link_to u.name, u %></b></p>
        <% end %>
      <% else %>
        <p>You must be logged in as the administrator to access this feature.</p>

      <% end %>
      

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Create new user</h2>
    </div>
  </div>
</div>

<%= render 'users/form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Profile</h2>
    </div>
    <div class="large-12 medium-12 small-12 columns">
      <% if !current_user.nil? %>
      <%= link_to 'Back to users', users_path %>
      
         | <%= link_to 'Edit', edit_user_path %> 
         | <%= link_to 'Delete', @user, method: :delete, data: {confirm: "Are you sure you wish to delete?"} %>
      
        <h3><%= @user.name %></h3>
        <p><b>Email:</b> <%= @user.email %></p>
      <%else%>
        <p>You must be logged in as the administrator to access this feature.</p>

      <% end %>
    </div>
  </div>
</div>