idl/config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#index'

  get 'pages/index'
  get 'pages/people'
  get 'pages/projects'
  get 'pages/publications'
  get 'pages/contact'

  get 'people' => 'people#index'
  get 'users' => 'users#index'
  get 'projects' => 'projects#index'
  get 'publications' => 'publications#index'

  get '/publications/:id/edit' => 'publications#edit'
  get '/publications/indexall' => 'publications#indexall'

  delete '/' => 'sessions#destroy'
  delete '/users' => 'sessions#destroy'
  delete '/people' => 'sessions#destroy'
  delete '/projects' => 'sessions#destroy'
  delete '/publications' => 'sessions#destroy'
  delete '/pages/contact' => 'sessions#destroy'

  resources :projects
  resources :users
  resources :sessions
  resources :people
  resources :publications

end

idl/app/models/page.rb
class Page < ActiveRecord::Base
end

idl/app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :title
end

idl/app/models/project.rb
class Project < ActiveRecord::Base
    validates_presence_of :title
    validates_presence_of :description
    validates_presence_of :people
end

idl/app/models/publication.rb
class Publication < ActiveRecord::Base
  validates_presence_of :year
  validates_presence_of :citation
end

idl/app/models/session.rb
class Session < ActiveRecord::Base
    belongs_to :user

    def save_with_session_code
      self.session_code = SecureRandom.urlsafe_base64 unless self.session_code
      self.save
    end
end

idl/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password
  has_secure_password

end

idl/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

idl/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def people
  end

  def projects
  end

  def publications
  end

  def contact
  end
end

idl/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
      @people = Person.all
    end

    def show
      @person = Person.find(params[:id])
      respond_to do |format|
          format.html
          format.json {render json: @user}
        end
    end

    def new
        @person = Person.new
    end

    def create
        @person = Person.create(person_params)
        redirect_to @person
    end

    def person_params
      params.require(:person).permit(:name, :title, :site, :contact, :projects)
    end

    def edit
        @person = Person.find(params[:id])
    end

    def update
        @person = Person.find(params[:id])
        respond_to do |format|
            if @person.update(person_params)
                format.html {redirect_to @person, notice: 'Person was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @person.errors, status: :unprocessable_entity}
            end
        end
    end
end

idl/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
      @projects = Project.all
    end

    def show
      @projects = Project.find(params[:id])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.create(project_params)
        redirect_to @project
    end

    def project_params
      params.require(:project).permit(:title, :people, :description)
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        respond_to do |format|
            if @project.update(project_params)
                format.html {redirect_to @project, notice: 'Project was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @project.errors, status: :unprocessable_entity}
            end
        end
    end

    def destroy
      @project = Project.find(params[:id])
      @project.destroy
      redirect_to projects_path
  end
end

idl/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      s = Session.new(user_id: user.id)
      s.save_with_session_code
      cookies.permanent[:session_code] = s.session_code
      redirect_to root_url
    else 
      render text: 'Incorrect email or password.'
    end
  end

  def destroy
    #session[:current_user] = nil
    #flash[:notice] = "You have successfully logged out."
    cookies.delete :session_code
    #session.delete(:user_id)
    @current_user = nil
    redirect_to root_url
  end
end

idl/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @user}
    end
  end

  def new
    @user = User.new
  end

  def admin
    @user = User.create(name: "Administrator", email: "admin@email.com", password: "x")
  end

  include SessionsHelper
  def create
      @user = User.create(user_params)
      s = Session.new(user_id: @user.id)
      s.save_with_session_code
      cookies.permanent[:session_code] = s.session_code
      redirect_to @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

   def edit
        @user = User.find(params[:id])
    end



    def update
        @user = User.find(params[:id])
        respond_to do |format|
            if @user.update(user_params)
                format.html {redirect_to @user, notice: 'User was successfully updated.'}
                format.json {head :no_content}
            else
                format.html {render action: 'edit'}
                format.json {render json: @user.errors, status: :unprocessable_entity}
            end
        end
    end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
  end
end

idl/app/helpers/application_helper.rb
module ApplicationHelper
end

idl/app/helpers/page_helper.rb
module PageHelper
end

idl/app/helpers/pages_helper.rb
module PagesHelper
end

idl/app/helpers/people_helper.rb
module PeopleHelper
end

idl/app/helpers/projects_helper.rb
module ProjectsHelper
end

idl/app/helpers/publications_helper.rb
module PublicationsHelper
end

idl/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user(*args)
    x = Session.includes([:user => (args.nil? ? [] : args)]).find_by(:session_code => cookies[:session_code])
    @current_user = x.nil? ? nil : x.user
  end

end

idl/app/helpers/users_helper.rb
module UsersHelper
end

idl/app/views/layouts/_footer.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user.nil? %>
          <li><%= link_to "Login", new_session_path %></li>
        <% else %>
          <li><%= link_to "Logout", @session, method: :delete, data: {confirm: "Are you sure you wish to logout?"} %></li>
        <% end %>
      </ul>
    </section>

  </nav>
</div>

idl/app/views/layouts/_navigation.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">

    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "IDL", root_url %></h1>
      </li>
    
      <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if !current_user.nil? %>
          <li><%= link_to "Users", users_path %></li>
        <% end %>
        <li><%= link_to "People", people_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Publications", publications_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
    </section>

  </nav>
</div>

idl/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Interaction Design Lab" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="row show-for-medium-up">
      <div class="large-12 medium-12 columns">
        <h1><%= link_to "INTERACTION DESIGN LAB", root_url %></h1>
      </div>
    </div>

    <div class="row show-for-small-only">
      <div class="small-12 columns">
        <h1><%= link_to "INTERACTION DESIGN LAB", root_url %></h1>
      </div>
    </div>



    <%= yield %>
    <%= javascript_include_tag "application" %>

    <%= render 'layouts/footer' %>
  </body>
</html>

idl/app/views/pages/contact.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Contact</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
      <div class="large-6 medium-6 small-12 columns">
      <form>
        <label>Name
        <input type="text" placeholder="Name" />
        </label>

        <label>Email Address </label>
        <input type="text" placeholder="person@example.com" />

        <label>Subject
        <input type="text" placeholder="e.g. Prospective Student" />
        </label>

        <label>Message
        <textarea placeholder="Message here"></textarea>
        </label>



        <a role="button" aria-label="submit form" href="#" class="button right">Submit</a>
      </form>
      </div>
      </div>
  </div>
</div>

idl/app/views/pages/index.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Overview</h2>
    </div>
    
    <div id="intro">
      <p>The <b>Interaction Design Lab</b> explores social and technical issues in the design, implementation, and evaluation of information and 
        communication technologies. We conduct research in mobile computing, technologies for health and wellness, social networking, 
        affective computing, design theory, and related areas. Our work seeks to understand how technology can help enable more 
        healthy, socially connected, and reflective living.
      </p>
    </div>

  </div>
</div>

<div class="row">
  <div class="large-12 medium-12 small-12 columns"> 
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Focus Areas</h2>
    </div>
  
    <ul class="gridblock_ul large-block-grid-4 medium-block-grid-4 small-block-grid-1">
      <li class="gridblock">
        <h3><b>Mediated Participation</b></h3>
        <h1><img alt="Mediated Participation" src="/assets/medpart_fa.png"></h1>
        <p>Creative ways of fostering engagement and ways of fostering creative engagement</p>
      </li>
      
      <li class="gridblock">
        <h3><b>Mobile Health</b></h3>
        <h1><img alt="Mobile Health" src="/assets/mobhealth_fa.png"></h1>
        <p>Better measuring physiological health characteristics and understanding the relationship between behavioral or psychological measures and actual health outcomes</p>
      </li>
      
      <li class="gridblock">
        <h3><b>Social Networks</b></h3>
        <h1><img alt="Social Networks" src="/assets/socialnet_fa.png"></h1>
        <p>Understanding how mobile phones can be used to employ social interactions and interventions   to encourage healthy behavior</p>
      </li>
      
      <li class="gridblock">
        <h3><b>Sustainable Design</b></h3>
        <h1><img alt="Sustainable Design" src="/assets/sustdes_fa.png"></h1>
        <p>Focusing on broad cultural understandings of sustainability and everyday practices</p>
      </li>
    </ul>
  </div>
</div>

idl/app/views/pages/people.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Director</h2>
    </div>

    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <li class="gridblock">
        <h3>Geri Gay</h3>
        <h1>[IMAGE]</h1>
        <b>Faculty</b>
      </li>
    </ul>
    
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Postdoctoral Scholars</h2>
    </div>
    
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <li class="gridblock">
        <h3>Eric Baumer</h3>
        <h1>[IMAGE]</h1>
        <b>Research Associate</b><br/>
        Frame Reflections
      </li>
    </ul>
    
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Graduate Students</h2>
    </div>
    
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <li class="gridblock">
        <h3>Jean Costa</h3>
        <h1>[IMAGE]</h1>
        <b>2nd Year Ph.D Student</b><br/>
        MoodRhythm
        </li>
      <li class="gridblock">
        <h3>Jean Costa</h3>
        <h1>[IMAGE]</h1>
        <b>2nd Year Ph.D Student</b><br/>
        MoodRhythm
      </li>
      <li class="gridblock">
        <h3>Jean Costa</h3>
        <h1>[IMAGE]</h1>
        <b>2nd Year Ph.D Student</b><br/>
        MoodRhythm
      </li>
      <li class="gridblock">
        <h3>Jean Costa</h3>
        <h1>[IMAGE]</h1>
        <b>Ph.D Student, 2nd Year</b><br/>
        MoodRhythm
        </li>
    </ul>
    
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Undergraduate Students</h2>
    </div>
    
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <li class="gridblock">
      <h3>Jung-Ho Sohn</h3>
      <h1>[IMAGE]</h1>
      <b>Senior, Fine Arts & Information Science </b><br/>
      Frame Reflections
        </li>
      <li class="gridblock">
      <h3>Jung-Ho Sohn</h3>
      <h1>[IMAGE]</h1>
      <b>Senior, Fine Arts & Information Science </b><br/>
      Frame Reflections
        </li>
      <li class="gridblock">
      <h3>Jung-Ho Sohn</h3>
      <h1>[IMAGE]</h1>
      <b>Senior, Fine Arts & Information Science </b><br/>
      Frame Reflections
        </li>
      <li class="gridblock">
      <h3>Jung-Ho Sohn</h3>
      <h1>[IMAGE]</h1>
      <b>Senior, Fine Arts & Information Science </b><br/>
      Frame Reflections
        </li>
    </ul>
    
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Alumni</h2>
    </div>
    
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4 small-block-grid-1">
      <li class="gridblock">
      <h3>J.P. Pollak</h3>
      <h1>[IMAGE]</h1>
      <b>Information Science </b><br/>
      Vera+
        </li>
      <li class="gridblock">
      <h3>J.P. Pollak</h3>
      <h1>[IMAGE]</h1>
      <b>Information Science </b><br/>
      Vera+
        </li>
    </ul>
    
  </div>
</div>

idl/app/views/pages/projects.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Current Projects</h2>
    </div>
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4">
      <li class="gridblock">
      <h3>mood.cloud</h3>
      <h1>[IMAGE]</h1>
      Combining art and interaction design, we are showcasing the “mood” of 
campus light by collecting feelings of passersby in a public space.
        </li>
      
    </ul>
    
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Past Projects</h2>
    </div>
    
    <ul class="gridblock_ul medium-block-grid-3 large-block-grid-4">
      <li class="gridblock">
      <h3>Facebook Non-use</h3>
      <h1>[IMAGE]</h1>
      Studying why and how people do not
use Facebook.
        </li>
      
    <li class="gridblock">
      <h3>Facebook Non-use</h3>
      <h1>[IMAGE]</h1>
      Studying why and how people do not
use Facebook.
        </li>
      <li class="gridblock">
      <h3>Facebook Non-use</h3>
      <h1>[IMAGE]</h1>
      Studying why and how people do not
use Facebook.
        </li>
      <li class="gridblock">
      <h3>Facebook Non-use</h3>
      <h1>[IMAGE]</h1>
      Studying why and how people do not
use Facebook.
        </li>
    </ul>
    
  </div>
</div>

idl/app/views/pages/publications.html.erb
<div class="row">
  <div class="large-12 medium-12 small-12 columns">
    <div class="headerbar large-12 medium-12 small-12 columns">
      <h2>Publications</h2>
    </div>
    
    <div id="tabshift">
    <dl id="tabsrow" class="tabs" data-tab>
      <dd class="active"><a href="#panel2014">2014</a></dd>
      <dd><a href="#panel2013">2013</a></dd>
      <dd><a href="#panel2012">2012</a></dd>
      <dd><a href="#panel2011">2011</a></dd>
    </dl>
    </div>
    
    <div id="tabscontent" class="tabs-content">
      <div class="content active" id="panel2014">
      <p>Abdullah, S., Matthews, M., Murnane, E., Gay, G. & Choudhury, T. 2014. Circadian Computing: How “Early to Bed and Early to 
Rise” Makes Some of Us Unhealthy and Sleep Deprived. Ubicomp 2014.
      </p>
      </div>
      <div class="content" id="panel2013">
      <p>This is the second panel of the basic tab example. This is the second panel of the basic tab example.</p>
      </div>
      <div class="content" id="panel2012">
      <p>This is the third panel of the basic tab example. This is the third panel of the basic tab example.</p>
      </div>
      <div class="content" id="panel2011">
      <p>This is the fourth panel of the basic tab example. This is the fourth panel of the basic tab example.</p>
      </div>
    </div>
  </div>
</div>